### ISSUE TITLE
Cyber Coach Models

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#10]
:clock1: **9h**
* Create a CyberCoachUser, CyberCoachRealation etc
* Make an abstract function that later will use CyberCoach

**Comment by sebyx31** [comment]
:clock1: 40m
* Tried using the ActiveResource gem recommended by @facenord-sud. The CyberCoach API is not at all compliant with Rails' philosophy, so this gem is not at all usable in our case.
:clock1: 1h
* Second try using the ActiveRestClient gem. It is possible to query the API with only a few lines of code. However, as with the other gem, the CyberCoach API is based on its own philosophy. Model class for the User resource in 945776c9a326e7880c0591ffb24dd5e8b41afa96.

:thought_balloon: Will probably try a less Ruby-ish and more manual approach.

**Comment by sebyx31** [comment]
:clock1: **3h** Implement model classes using ActiveModel::Model and connect the User to the API.

**Comment by sebyx31** [comment]
:clock1: **1h** Factorize common things in a CyberCoach superclass. Basic functionality usable, needs more work to connect all classes to the API.
