### ISSUE TITLE
Cyber Coach Fight

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#15]
:clock1: **5h**

**Comment by facenord-sud** [comment]
I have a 401 response code and I don't understand why!!!

See `spec/models/cybercoach/subscription_spec.rb` to reproduce the error.

HELP!!!

**Comment by facenord-sud** [comment]
I find it. There was a bug in the CyberCoach user. It was normalizing the username whatever it was for authentication but not normalizing for the param in the uri. We where creating a user with a non normalized username but, after that we were authenticating with a normalized username

**Comment by facenord-sud** [comment]
It is almost done. I just need to write some tests, to ensure I did it correctly for saving the right entities in CyberCoach from a FightClub fight. The API will not change anymore and it should work,

NB: A lot of refractoring have been done to avoid boilerplate code

**Comment by facenord-sud** [comment]
5h
