### ISSUE TITLE
Cyber Coach Hooks

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#17]
:clock1: **5h**

Helper and Hooks functions

**Comment by sebyx31** [comment]
Classes on which to add hooks:

* User
    * before_save (fail on CyberCoach failure?)
* Fight
    * before_create -> Create partenership, subscription
    * before_update -> Confirm partnership

One partnership per couple of users. Do a get on CyberCoach before trying to update.

**Comment by facenord-sud** [comment]
* Fight
  * before_update -> When a user win the fight. Create an boxing entry in the CyberCoach DB

**Comment by facenord-sud** [comment]
30min. I wait until all the tests are not broken anymore and I can write a test to show it works. But it should.

**Comment by facenord-sud** [comment]
15min more. Total 45min
