### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#2]
:clock1: **6h**
* Login
* Create account
* Edit account
* Logout

**Comment by younos** [comment]
:clock1: **6h**
Done.
Check the user views and devise views

**Comment by facenord-sud** [comment]
I cannot login or create an account. I have the error 404

    ActiveRecord not found can not find a User with id 'sign_up'

And it would be good to update the features or to make it pass, when problems are corrected.

**Comment by facenord-sud** [comment]
I did a fresh clone of the branch develop and it still does't work

**Comment by younos** [comment]
It works on feature branch "role_management". I'm waiting on Thibaut to finish his issue to then merge the branch with develop.
