### ISSUE TITLE
Design Basics

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#21]
:clock1: **2h**

**Comment by samtdr** [comment]
i did the forms and stuff i had in my mind, tell me if i missed anything for now :)

**Comment by tibm** [comment]
Thank you!
Actually on my forms "transactions" there is still white on white.
And the link "new transaction" is not clickable if a lot of transactions (it is under the footer I think...)

**Comment by samtdr** [comment]
fixed it!
