### ISSUE TITLE
Logic Fight

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#25]
:clock1: **5h**

Finish model + controller + view

**Comment by tibm** [comment]
:clock1: **2h**
Little improvement on views and 2 new routes and navigation

**Comment by younos** [comment]
:clock1: **4h**
Improve controller, model and view.
TODO: see fight_controller

:clock1: **1h**
Add model tests for fight

**Comment by tibm** [comment]
Small bug displaying fights. Found NIL before calling fighter_name() in view. Happens for example if the adversary is not yet set. Very strange actually. We test tomorrow, ok?
