### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by facenord-sud** [ase-15/fightclub#27]
:clock1: **1h**

Deploy on Heroku

**Comment by sebyx31** [comment]
[Deployed](https://e-fightclub.herokuapp.com/).

Merge to master pending for comments

**Comment by tibm** [comment]
What do you mean with "merge to master pending for comments"? For me you can merge to master... Such as I can test the Paypal hooks...

**Comment by sebyx31** [comment]
The application is deployed on Heroku, test it and if there are Heroku-specific modifications, push them to milestone2. When we are confident that the site is functioning properly, we can merge to master.

**Comment by tibm** [comment]
Well... actually nothing works since I cannot login... Unable to create an account and Facebook login is also not working... in think this is a VERY URGENT issue, since it is the base of our app... I guess it is only a small issue, since it seems to have problems with API-keys

**Comment by sebyx31** [comment]
:clock1: **2h** Done
