### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by sebyx31** [ase-15/fightclub#33]
:clock1: **8h**

Web notifications and e-mails

**Comment by younos** [comment]
:clock1: **3h**

Look at the work done by @tibm and @facenord-sud on a previous app.
Set base files for notifications.

TODO:
* Create notifications during actions
* Add notifications in layout

**Comment by younos** [comment]
:clock1: **6h**

* Fighter adversary can accept/refuse a fight
* Fighter creator and adversary can vote
* Real winner is automatically set if votes are equal
* Admin receives a notification if votes are not equal and can set real winner
* Notifications are sent during these steps
