### ISSUE TITLE
Sort/filter fights index

### ISSUE THREAD

**Issue by sebyx31** [ase-15/fightclub#48]
:clock1: **2h**

Add sort and filter/search functionality to the fights list

**Comment by tibm** [comment]
Is a jquery plugin ok for you? 
Because: 
> sorting makes no sense (we have the selection in the menu [upcoming / passed / mine] and time sort is default and makes sense
> for filtering if less than 200 fights per page, what is realistic for us, jquery (hide/show) will work.

If you don't agree please help me with a gem proposition. I'll start this part on friday

**Comment by younos** [comment]
Ok for me for using jquery for filtering only.

**Comment by tibm** [comment]
:clock1: **1h** 

Solved with JQuery and nice CSS ;)
