### ISSUE TITLE
Autogenerated default profile picture

### ISSUE THREAD

**Issue by sebyx31** [ase-15/fightclub#49]
:clock1: **30min**

**Comment by sebyx31** [comment]
Example with Gravatar given by @facenord-sud :
```ruby
def avatar_url(user)
  if user.avatar_url.present?
    user.avatar_url
  else
    default_url = "#{root_url}images/guest.png"
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d=#{CGI.escape(default_url)}"
  end
end
```

**Comment by tibm** [comment]
:clock1: **1h**

Actually done also some other stuff, (fight home page design), but I didn't use Gravatar (it is not a db of images, but more a global profile). So I used http://api.randomuser.me but we could use lorempixel also...
