### ISSUE TITLE
Travis, Git Hook & Heroku

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#5]
:clock1: **3h**
* Travis: Tests
* Git Hook: Control commits
* Heroku: Deploy on master push

**Comment by facenord-sud** [comment]
* Git hooks are configured. Refer to the corresponding wiki page and don't forget to enable git hooks:
```bash
gem install overcommit
overcommit --install
```
In the repo
* Test are run on Travis, see the README
* Everyone must use git flow from now!!!

**Comment by tibm** [comment]
Hey @facenord-sud same for you, can you please just add the number of hours you worked on this issue? Like it is written in the WIKI. Thanks :+1:

**Comment by facenord-sud** [comment]
3h
