### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by sebyx31** [ase-15/fightclub#54]
:clock1: **3h**

Complete the homepage with real info.

**Comment by tibm** [comment]
Ehm... partially done I would say...

:clock1: **1h** 

I did this while doing the "about" page, was very quickly done, but also not very nice...

**Comment by samtdr** [comment]
Thanks Thibaut. I was planning to work on my issues on the weekend since the priorities wasn't high. but you got me;) sorry for the trouble.
