### ISSUE TITLE
Design: various minor issues

### ISSUE THREAD

**Issue by sebyx31** [ase-15/fightclub#57]
Add issues below.

- [x] notification div height
- [x] footer css in firefox
- [x] add fight details in maps infowindow
- [x] justified alignment in forms
- [x] change font
- [x] fight description
- [x] fire fox design issues
- [x] fix add fight button on firefox

**Comment by tibm** [comment]
@samtdr Please finish/close this issue and add duration. The project needs to be finished for tomorrow...

**Comment by samtdr** [comment]
total time: 4h
