### ISSUE TITLE
Constraint

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#6]
:clock1: **2h**
* Model constraints
* Format (email, name)
* Think about CyberCoach constraints

**Comment by facenord-sud** [comment]
Update the specs if the constraints differs from them

**Comment by facenord-sud** [comment]
the specs are in the branch feature/user_features

**Comment by younos** [comment]
Some ideas:
* A Fighter should not be able to fight against himself
* A Fighter should not be able to bet for his opponent, but only for himself
* A gambler should not be able to bet two times on the same fight
* Depending on how we decide to manage the money account of a gambler, he should not be able to have a negative balance of transaction (before a bet is made, should check if the sum of transactions is enough, or before he decides to take back money same thing)
* Think about uniqueness of fields if not already done (username/email should already be done by devise, but display_name not -> can be good to avoid "The Evil vs The Evil")
* ...
