### ISSUE TITLE
Augment GeoHash precision

### ISSUE THREAD

**Issue by sebyx31** [ase-15/fightclub#61]
:clock1: **10 min**

11 seems a reasonable value.

Length | Cell width |	Cell height
-----|-----|------
1 | ≤ 5,000km | 5,000km
2|	≤ 1,250km	|	625km
3|	≤ 156km	|	156km
4|	≤ 39.1km	|	19.5km
5|	≤ 4.89km	|	4.89km
6|	≤ 1.22km	|	0.61km
7|	≤ 153m	|	153m
8|	≤ 38.2m	|	19.1m
9|	≤ 4.77m	|	4.77m
10|	≤ 1.19m	|	0.596m
11|	≤ 149mm	|	149mm
12|	≤ 37.2mm	 |	18.6mm

**Comment by Nikowned** [comment]
:clock1: **10minutes**
