### ISSUE TITLE
Feature testing

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#69]
:clock1: **Undetermined time**

>Testing is never finish and can always be improved.

Because this is a special issue, I propose to organize as follow:

- Write in __the above__ message all the possible feature tests with an unchecked checkbox [ ]
- When you decide to work on a listed test, drop a message in this issue.
- When a test is realized check the checkbox [x]
- It is up to you to write feature tests, but better tests we have, better our project will be (in the point of view of software engineering and the objectives of this course)

By feature test I mean: tests written with cucumber, RSpec and capybara describing the user interaction. I let you read the [wiki](https://github.com/ase-15/fightclub/wiki/Testing), the doc (follow the links in the wiki to get started) and the existing tests to have an idea.

### Formular
By formular, we mean testing form for correct values entered and as well as all possible bad values. check this [feature](https://github.com/ase-15/fightclub/blob/develop/features/form.feature)

- [ ] sign in
- [ ] Sign up
- [ ] Edit profile
- [x] Create a fight
- [ ] Edit a fight
- [ ] Vote for a winner (as admin and as fighter)
- [ ] Load wallet
- [ ] Refund wallet
- [ ] Bet on a fight

## General user interaction
Maybe some tests can be grouped in one

- [ ] Observe {all, upcoming, passed} fights on a map (tricky)
- [ ] Search for a fight
- [ ] Check {upcoming, passed, created, accepted} fights display
- [ ] Pagination for the fights
- [ ] The possible kind of transactions (pending, accepted, more?)
- [ ] Pagination for transactions
- [ ] Display for bets
- [ ] Pagination for bets
- [ ] Notifications
- [ ] Display of the profile
- [ ] Logout

## Tricky tests

Here are the tricky tests.

Nota: the test have to be fully automated

- [ ] Log in with Facebook
- [ ] Post to Facebook
- [ ] Add a location by clicking on the map

## Easy tests

- [x] Display of home page
- [x] Display of about page

**Comment by facenord-sud** [comment]
## Feature tests

### Formular
By formular, we mean testing form for correct values entered and as well as all possible bad values. check this [feature](https://github.com/ase-15/fightclub/blob/develop/features/form.feature)

**Comment by tibm** [comment]
@younos How fare are we here? I suggest we finish coding today and close all issues for tomorrow. Because we really should push to Heroku for final tests tomorrow.

**Comment by younos** [comment]
@tibm That's not a problem if I only update features testing files as we need for local tests only. And if we need to show something about it during the presentation we can it locally only. So this issue can remain open during this week at least I think.

**Comment by younos** [comment]
Forgot to implement all feature tests for deadline
