### ISSUE TITLE
View ask for password when updating profile

### ISSUE THREAD

**Issue by younos** [ase-15/fightclub#79]
- [x] When we try to update our own profile, in edit view we see the info "we need your current password to confirm your changes" while in fact we don't need it
- [x] The "current password" field is also in red
- [x] There is also a bug with the edit button showing "<SPAN CLASS="

![bug](https://cloud.githubusercontent.com/assets/7117622/11394571/4092a8c6-9366-11e5-81b9-a266ea410c29.png)

**Comment by tibm** [comment]
@samtdr can you quickly check the CSS? If it is not sufficient I can help. Or even do it :smile:. Thank you!

**Comment by samtdr** [comment]
@tibm Oh...I'm soooo sorry . I didn't noticed this comment just until now. I will fix it, today don't worry.
