### ISSUE TITLE
Business Logic Test

### ISSUE THREAD

**Issue by tibm** [ase-15/fightclub#8]
:clock1: **6h**
* Simple unit tests
  * Does a Bid correspond to a User
  * Test methods 
  * Test relations

**Comment by tibm** [comment]
:clock1: **5h**
NO RESULTS! Really tried with FactoryGirl, but no chance. It is complex to create a fight. You need to reference two different users to the fields... Anyway, if someone want to help, please (the feature branch is created). But I'll focus on other stuff without help.

**Comment by facenord-sud** [comment]
I write it simple tests like testing constraints and relations

1h30

**Comment by facenord-sud** [comment]
I cannot find your commit

**Comment by tibm** [comment]
@facenord-sud yes, I didn't commit, since nothing worked :cry: do you close this issue then?
